export const Records = [
  {
    date: false,
    emotion: false,
    trigger: false,
    action: 'Engage',
    arousal: 1,
    conduciveness: 1,
    controllability: 3,
    intensity: 3,
    valence: 3,
  },
  {
    action:"Fight",
    arousal:2,
    conduciveness:2,
    controllability:2,
    date:"2017-05-31 12:32",
    emotion:"Joy",
    intensity:1,
    trigger:"Thing,Person",
    valence:4
  },
  {
    action:"Other",
    arousal:3,
    conduciveness:3,
    controllability:2,
    date:"2017-05-31 12:32",
    emotion:"Joy",
    intensity:5,
    trigger:"Activity",
    valence:5
  },
  {
    action:"Savor",
    arousal:4,
    conduciveness:4,
    controllability:3,
    date:"2017-06-01 12:32",
    emotion:"Joy",
    intensity:3,
    trigger:"Person",
    valence:3
  },
  {
    action:"Suppress",
    arousal:5,
    conduciveness:5,
    controllability:3,
    date:"2017-06-01 12:32",
    emotion:"Trust",
    intensity:3,
    trigger:"Person",
    valence:3
  },
  {
    action:"Withdraw",
    arousal:3,
    conduciveness:5,
    controllability:3,
    date:"2017-06-01 12:32",
    emotion:"Trust",
    intensity:3,
    trigger:"Place",
    valence:5
  },
  {
    action:null,
    arousal:3,
    conduciveness:5,
    controllability:3,
    date:"2017-06-01 12:32",
    emotion:null,
    intensity:3,
    trigger:null,
    valence:4
  },
  {
    action:"Fight",
    arousal:2,
    conduciveness:4,
    controllability:2,
    date:"2017-05-31 12:32",
    emotion:"Joy",
    intensity:2,
    trigger:"Activity",
    valence:2
  },
  {
    action:"Engage",
    arousal:3,
    conduciveness:5,
    controllability:3,
    date:"2017-06-01 12:32",
    emotion:"Joy",
    intensity:3,
    trigger:"Person",
    valence:3
  },
  {
    action:"Withdraw",
    arousal:3,
    conduciveness:4,
    controllability:3,
    date:"2017-05-31 12:32",
    emotion:"Joy",
    intensity:3,
    trigger:"Thing,Person",
    valence:3
  },
  {
    action:"Fight",
    arousal:2,
    conduciveness:4,
    controllability:2,
    date:"2017-05-31 12:32",
    emotion:"Joy",
    intensity:2,
    trigger:"Activity",
    valence:2
  },
  {
    action:"Engage",
    arousal:3,
    conduciveness:5,
    controllability:3,
    date:"2017-06-01 12:32",
    emotion:"Joy",
    intensity:3,
    trigger:"Person",
    valence:3
  },
  {
    action:"Fight",
    arousal:3,
    conduciveness:5,
    controllability:3,
    date:"2017-06-01 12:32",
    emotion:"Trust",
    intensity:3,
    trigger:"Person",
    valence:3
  },
  {
    action:"Fight",
    arousal:3,
    conduciveness:5,
    controllability:3,
    date:"2017-06-01 12:32",
    emotion:"Trust",
    intensity:3,
    trigger:"Place",
    valence:3
  },
  {
    action:null,
    arousal:3,
    conduciveness:5,
    controllability:3,
    date:"2017-06-01 12:32",
    emotion:null,
    intensity:3,
    trigger:null,
    valence:3
  },
  {
    action:"Fight",
    arousal:2,
    conduciveness:4,
    controllability:2,
    date:"2017-05-31 12:32",
    emotion:"Joy",
    intensity:2,
    trigger:"Activity",
    valence:2
  },
  {
    action:"Engage",
    arousal:3,
    conduciveness:5,
    controllability:3,
    date:"2017-06-01 12:32",
    emotion:"Joy",
    intensity:3,
    trigger:"Person",
    valence:3
  },
  {
    action:"Fight",
    arousal:3,
    conduciveness:5,
    controllability:3,
    date:"2017-06-01 12:32",
    emotion:"Trust",
    intensity:3,
    trigger:"Person",
    valence:3
  }
];
